spring:
    datasource:
        url: jdbc:mysql://localhost/sakila
        username: cs544
        password: 201511
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect